#!/usr/bin/env bash
# Next.js dashboard — reads sandbox/.env, writes sandbox/web/.env.local, runs dev.
# Usage: ./run-web.sh   (start ./run-api.sh in another terminal first)

set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
WEB="$ROOT/sandbox/web"

# shellcheck source=sandbox/env.sh
source "$ROOT/sandbox/env.sh"

API_URL="http://localhost:${API_PORT}"
ENV_LOCAL="$WEB/.env.local"

cat > "$ENV_LOCAL" <<EOF
# Auto-generated by run-web.sh from sandbox/.env — do not commit secrets elsewhere.
API_URL=${API_URL}
ANALYZE_API_KEY=${ANALYZE_API_KEY}
EOF

cd "$WEB"

if [[ ! -d node_modules ]]; then
  echo "Installing npm dependencies..."
  npm install
fi

echo "Web UI http://localhost:3000  →  API ${API_URL}"
exec npm run dev
